Added image conversion box to sidebar
Esser50K/90sYouTube pull request #17
Opened 2022-06-09 11:30 UTC by matedyl

Resolves #12

2022-06-11 12:34 UTC, Esser50K commented
I was able to test it before the conflicts, I like   where it is positioned now.
There are some things missing from the original one though. For example, when one is hovering the file over the style should be adapted to show it is "selected" and also a different style for the error cases (like filetype is not supported).
For reference this behaviour can still be seen on [asciifly](asciifly.com)

2022-06-11 13:37 UTC, Esser50K requested changes

2022-06-11 13:37 UTC, Esser50K commented on app/app/src/components/ImageInput.tsx
> -                        : "img-input-without-file")}
this part is now missing, the styles would change when a file is hovering, and there would be an "error" style for unsupported file formats

2022-06-15 10:14 UTC, matedyl commented on app/app/src/components/ImageInput.tsx
> -                        : "img-input-without-file")}
@Esser50K Thanks a lot! I've added the missing styles now ⬇️

2022-06-15 14:15 UTC, Esser50K commented on app/app/src/components/ImageInput.tsx
> +                            onDragOver={handleDrag}
I was testing this out and it seems like this doesn't work properly.
The previous approach with the `useEffect` was mostly taken from this [tutorial](https://medium.com/@650egor/simple-drag-and-drop-file-upload-in-react-2cb409d88929)

I didn't try to debug it but I'm assuming the `dragInCount` is affected differently. Basically I get a very jittery state when hovering over.
Probably works if you wrap the whole thing in a `div` and use that as reference and use the old approach.

2022-06-15 14:15 UTC, Esser50K commented on app/app/src/components/ImageInput.tsx
> +                    {inputText()}
Can we keep the box a constant size though? because when the inputText changes, so does the box size and everything on the sidebar moves up and down

2022-06-15 19:45 UTC, matedyl commented on app/app/src/components/ImageInput.tsx
> +                            onDragOver={handleDrag}
I reverted to the previous solution and it works well now. Could you check again?
I get the warning about the deps array and suggestion to remove it, but I see that you had that warning before too.

2022-06-17 08:49 UTC, Esser50K approved these changes

2022-06-17 08:49 UTC, merged