90fy it a bit more
Esser50K/90sYouTube pull request #18
Opened 2022-06-18 21:58 UTC by Esser50K

I added boxShadow on pretty much everything..

I changed the colors a bit. So to match youtube I would like the appbar and the drawer to have the same background color. But I'm having issues in getting it right for every style without breaking things, so for now it only is on the default youtube theme and poster. @matedyl maybe we can look at this together in a call.

Could you also review it because I'm not sure I'm following best practices and maybe I'm making it a mess again

2022-06-21 09:11 UTC, matedyl commented on app/app/src/pages/Layout.tsx
> +            ...gen3DBoxShadowStyle(2, theme),
I would rather put this on a theme level, as we need to have 'shadows' property defined anyway (explained it a bit more in the PR comment). Also - unless you want to have a special style for one instance of UI element, it should be defined in theme to properly override all components in the library.

2022-06-22 14:00 UTC, matedyl requested changes
Regarding changing the color of the sidebar, I suggest that you update the `palette.background.paper` property and the contrast text should update automatically for the regular text ([see docs](https://v4.mui.com/customization/palette/#providing-the-colors-directly)). For the button text color, you can choose a different color with the `color` property itself (e.g. `color='secondary'`).

Let me know in case none of the colors available work and we can think of extending some of the themes.

2022-06-22 14:00 UTC, matedyl commented on app/app/src/components/YoutubeVideoThumbnail.tsx
> +            color: 'transparent'
This can be removed

2022-06-22 14:00 UTC, matedyl commented on app/app/src/pages/Layout.tsx
> -                        { isDesktop &&
I think it's okay to remove it for now, but we need to test with users after Watch page is done to see whether it's clear how the converting works without the label.

2022-06-22 14:00 UTC, matedyl commented on app/app/src/themeSelector/themes/poster/index.ts
> +            disableElevation: true,
Remember to remove this when you bring back the `shadows` property.

2022-06-23 08:31 UTC, Esser50K commented on app/app/src/components/YoutubeVideoThumbnail.tsx
> +            color: 'transparent'
I actually checked and the color was also influencing the background color of the hover state 😕 I added a comment so that we don't get confused at a later time

2022-06-23 08:38 UTC, Esser50K commented on app/app/src/themeSelector/themes/poster/index.ts
> +            disableElevation: true,
so I brought back the shadows property and it works ok.
However I didn't like the button behaviour at all, it was using more shadow layers when pressed and the effect just didn't look nice.

Therefor I created a new component called `ElevatedButton` that has all the styles for the different states so we can use that one.

2022-06-23 08:40 UTC, Esser50K commented on app/app/src/pages/Layout.tsx
> -                        { isDesktop &&
yeah or we can put the label as a placeholder instead of a youtube URL

2022-06-29 12:29 UTC, merged