Watch page layout (desktop)
Esser50K/90sYouTube pull request #19
Opened 2022-08-11 16:56 UTC by matedyl

https://app.clickup.com/t/2zh2dhz

2022-08-12 14:55 UTC, Esser50K reviewed
still have to checkout the branch and take a look

2022-08-12 20:31 UTC, Esser50K requested changes
Tested it now.

I see that the video recommendations are on the right side now, but it won't collapse to a single column. I'd prefer to get this right in this PR because I'd like that every commit on Master is deployable (even when I don't deploy it)

2022-08-13 10:49 UTC, matedyl commented on app/app/src/components/AsciiPlayer.tsx
> +        const fontAdjustment = 1.1  // scale adjustment for fitting the text block to the container width - depends on the width of the character in font family
@Esser50K I added it to fit the YT layout as closely as possible and due to the way font rendering works: it is not fully responsive and renders font in the same size for a range of `font-size` values. It has some implications on how closely the design can match YT watch page. Let's schedule a call soon and I can explain it further!

2022-08-13 11:01 UTC, matedyl commented
> 



> Tested it now.
> 
> I see that the video recommendations are on the right side now, but it won't collapse to a single column. I'd prefer to get this right in this PR because I'd like that every commit on Master is deployable (even when I don't deploy it)

Could you explain what you mean by collapsing to a single column? After testing I see that the main layout is a column: with video on the top and recommended vids section on the bottom.

2022-09-25 14:21 UTC, Esser50K approved these changes

2022-09-25 14:21 UTC, merged